# Generated by Django 4.2.3 on 2023-07-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.CharField(blank=True, max_length=200, null=True)),
                ('scraped_email', models.IntegerField(default=0)),
                ('isRuning', models.BooleanField(default=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('isStop', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
