# Generated by Django 3.2.18 on 2023-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontroller',
            name='total_acc',
            field=models.IntegerField(default=0),
        ),
    ]
