# Generated by Django 3.2.18 on 2023-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_processcontroller_list_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontroller',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
